### ISSUE TITLE
no data arrives at server from MAC 

### ISSUE THREAD

**Issue by hendrikknoche** [med-material/TunnelGoalFittsTests#59]
hmm, this used to work.

**Comment by bastianilso** [comment]
In the server logs I see
`[Mon Mar 29 00:54:14.463788 2021] [:error] [pid 68879] [client 172.29.52.193:63028] execute() failed: Incorrect integer value: '' for column 'PID' at row 1`
I guess this can have happened if you entered a PID number and removed it again. I have added safety clauses now, so that it isnt possible to send an empty value.
